# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.models.groups_index import GroupsIndex

class TestGroupsIndex(unittest.TestCase):
    """GroupsIndex unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GroupsIndex:
        """Test GroupsIndex
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GroupsIndex`
        """
        model = GroupsIndex()
        if include_optional:
            return GroupsIndex(
                api_version = '',
                items_count = 56,
                total_items = 56,
                limit = 56,
                offset = 56,
                next_item = 56,
                next_link = '',
                item_type = '',
                items = [
                    lgl_openapi_3_0_client.models.group_response.GroupResponse(
                        id = 56, 
                        name = '', 
                        key = '', 
                        ordinal = 56, )
                    ]
            )
        else:
            return GroupsIndex(
                api_version = '',
                items_count = 56,
                total_items = 56,
                limit = 56,
                offset = 56,
                next_item = 56,
                next_link = '',
                item_type = '',
                items = [
                    lgl_openapi_3_0_client.models.group_response.GroupResponse(
                        id = 56, 
                        name = '', 
                        key = '', 
                        ordinal = 56, )
                    ],
        )
        """

    def testGroupsIndex(self):
        """Test GroupsIndex"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
