# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.models.note_response import NoteResponse

class TestNoteResponse(unittest.TestCase):
    """NoteResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NoteResponse:
        """Test NoteResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NoteResponse`
        """
        model = NoteResponse()
        if include_optional:
            return NoteResponse(
                id = 56,
                constituent_id = 56,
                note_type_id = 56,
                note_type_name = '',
                text = '',
                external_id = '',
                original_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return NoteResponse(
                id = 56,
                constituent_id = 56,
                text = '',
                original_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
        )
        """

    def testNoteResponse(self):
        """Test NoteResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
