# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.models.notes_show import NotesShow

class TestNotesShow(unittest.TestCase):
    """NotesShow unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NotesShow:
        """Test NotesShow
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NotesShow`
        """
        model = NotesShow()
        if include_optional:
            return NotesShow(
                api_version = '',
                id = 56,
                constituent_id = 56,
                note_type_id = 56,
                note_type_name = '',
                text = '',
                external_id = '',
                original_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return NotesShow(
                api_version = '',
                id = 56,
                constituent_id = 56,
                text = '',
                original_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
        )
        """

    def testNotesShow(self):
        """Test NotesShow"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
