# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.models.campaign_update import CampaignUpdate

class TestCampaignUpdate(unittest.TestCase):
    """CampaignUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CampaignUpdate:
        """Test CampaignUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CampaignUpdate`
        """
        model = CampaignUpdate()
        if include_optional:
            return CampaignUpdate(
                id = 56,
                name = '',
                description = '',
                financial_goal = 1.337,
                start_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                end_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                code = ''
            )
        else:
            return CampaignUpdate(
                name = '',
        )
        """

    def testCampaignUpdate(self):
        """Test CampaignUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
