# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.models.group_memberships_show import GroupMembershipsShow

class TestGroupMembershipsShow(unittest.TestCase):
    """GroupMembershipsShow unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GroupMembershipsShow:
        """Test GroupMembershipsShow
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GroupMembershipsShow`
        """
        model = GroupMembershipsShow()
        if include_optional:
            return GroupMembershipsShow(
                api_version = '',
                id = 56,
                constituent_id = 56,
                group_id = 56,
                group_name = '',
                date_start = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                date_end = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                is_current = True,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return GroupMembershipsShow(
                api_version = '',
                id = 56,
                constituent_id = 56,
                group_id = 56,
        )
        """

    def testGroupMembershipsShow(self):
        """Test GroupMembershipsShow"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
