# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.models.mailing_templates_show import MailingTemplatesShow

class TestMailingTemplatesShow(unittest.TestCase):
    """MailingTemplatesShow unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MailingTemplatesShow:
        """Test MailingTemplatesShow
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MailingTemplatesShow`
        """
        model = MailingTemplatesShow()
        if include_optional:
            return MailingTemplatesShow(
                api_version = '',
                id = 56,
                name = '',
                code = True,
                mailing_type_id = 56,
                mailing_type_name = '',
                template_type = ''
            )
        else:
            return MailingTemplatesShow(
                api_version = '',
                id = 56,
                name = '',
        )
        """

    def testMailingTemplatesShow(self):
        """Test MailingTemplatesShow"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
