# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.models.relationship_types_index import RelationshipTypesIndex

class TestRelationshipTypesIndex(unittest.TestCase):
    """RelationshipTypesIndex unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RelationshipTypesIndex:
        """Test RelationshipTypesIndex
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RelationshipTypesIndex`
        """
        model = RelationshipTypesIndex()
        if include_optional:
            return RelationshipTypesIndex(
                api_version = '',
                items_count = 56,
                total_items = 56,
                limit = 56,
                offset = 56,
                next_item = 56,
                next_link = '',
                item_type = '',
                items = [
                    lgl_openapi_3_0_client.models.relationship_type_response.RelationshipTypeResponse(
                        id = 56, 
                        name = '', 
                        short_code = '', 
                        type_code = '', 
                        ordinal = 56, 
                        reciprocal_id = 56, 
                        auto_soft_credit = 56, 
                        is_spouse_partner = True, )
                    ]
            )
        else:
            return RelationshipTypesIndex(
                api_version = '',
                items_count = 56,
                total_items = 56,
                limit = 56,
                offset = 56,
                next_item = 56,
                next_link = '',
                item_type = '',
                items = [
                    lgl_openapi_3_0_client.models.relationship_type_response.RelationshipTypeResponse(
                        id = 56, 
                        name = '', 
                        short_code = '', 
                        type_code = '', 
                        ordinal = 56, 
                        reciprocal_id = 56, 
                        auto_soft_credit = 56, 
                        is_spouse_partner = True, )
                    ],
        )
        """

    def testRelationshipTypesIndex(self):
        """Test RelationshipTypesIndex"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
