# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.api.class_affiliations_api import ClassAffiliationsApi


class TestClassAffiliationsApi(unittest.TestCase):
    """ClassAffiliationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ClassAffiliationsApi()

    def tearDown(self) -> None:
        pass

    def test_lgl_api_v1_class_affiliations_create(self) -> None:
        """Test case for lgl_api_v1_class_affiliations_create

        Create new Class Affiliation
        """
        pass

    def test_lgl_api_v1_class_affiliations_destroy(self) -> None:
        """Test case for lgl_api_v1_class_affiliations_destroy

        Delete Class Affiliation
        """
        pass

    def test_lgl_api_v1_class_affiliations_update(self) -> None:
        """Test case for lgl_api_v1_class_affiliations_update

        Update Class Affiliation
        """
        pass

    def test_v1_class_affiliation(self) -> None:
        """Test case for v1_class_affiliation

        Show Class Affiliation details
        """
        pass

    def test_v1_constituent_class_affiliations(self) -> None:
        """Test case for v1_constituent_class_affiliations

        Fetch Class Affiliations
        """
        pass


if __name__ == '__main__':
    unittest.main()
