# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.models.membership_level_aggregated_response import MembershipLevelAggregatedResponse

class TestMembershipLevelAggregatedResponse(unittest.TestCase):
    """MembershipLevelAggregatedResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MembershipLevelAggregatedResponse:
        """Test MembershipLevelAggregatedResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MembershipLevelAggregatedResponse`
        """
        model = MembershipLevelAggregatedResponse()
        if include_optional:
            return MembershipLevelAggregatedResponse(
                id = 56,
                name = '',
                ordinal = 56
            )
        else:
            return MembershipLevelAggregatedResponse(
                id = 56,
                name = '',
        )
        """

    def testMembershipLevelAggregatedResponse(self):
        """Test MembershipLevelAggregatedResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
