# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.models.phone_numbers_index import PhoneNumbersIndex

class TestPhoneNumbersIndex(unittest.TestCase):
    """PhoneNumbersIndex unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PhoneNumbersIndex:
        """Test PhoneNumbersIndex
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PhoneNumbersIndex`
        """
        model = PhoneNumbersIndex()
        if include_optional:
            return PhoneNumbersIndex(
                api_version = '',
                items_count = 56,
                total_items = 56,
                limit = 56,
                offset = 56,
                next_item = 56,
                next_link = '',
                item_type = '',
                items = [
                    lgl_openapi_3_0_client.models.phone_number_response.PhoneNumberResponse(
                        id = 56, 
                        item_id = 56, 
                        item_type = '', 
                        number = '', 
                        phone_number_type_id = 56, 
                        phone_type_name = '', 
                        is_preferred = True, 
                        not_current = True, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return PhoneNumbersIndex(
                api_version = '',
                items_count = 56,
                total_items = 56,
                limit = 56,
                offset = 56,
                next_item = 56,
                next_link = '',
                item_type = '',
                items = [
                    lgl_openapi_3_0_client.models.phone_number_response.PhoneNumberResponse(
                        id = 56, 
                        item_id = 56, 
                        item_type = '', 
                        number = '', 
                        phone_number_type_id = 56, 
                        phone_type_name = '', 
                        is_preferred = True, 
                        not_current = True, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
        )
        """

    def testPhoneNumbersIndex(self):
        """Test PhoneNumbersIndex"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
