# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.models.gift_update import GiftUpdate

class TestGiftUpdate(unittest.TestCase):
    """GiftUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GiftUpdate:
        """Test GiftUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GiftUpdate`
        """
        model = GiftUpdate()
        if include_optional:
            return GiftUpdate(
                id = 56,
                external_id = 56,
                is_anon = True,
                gift_type_id = 56,
                gift_type_name = '',
                gift_category_id = 56,
                gift_category_name = '',
                campaign_id = 56,
                campaign_name = '',
                fund_id = 56,
                fund_name = '',
                appeal_id = 56,
                appeal_name = '',
                event_id = 56,
                event_name = '',
                received_amount = 1.337,
                received_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                payment_type_id = 56,
                payment_type_name = '',
                check_number = '',
                deductible_amount = 1.337,
                note = '',
                ack_template_name = '',
                deposit_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                deposited_amount = 1.337,
                parent_gift_id = 56,
                parent_external_id = 56,
                auto_sync_to_qbo = True,
                tribute_name = '',
                tributee_name = '',
                tribute_dedication = '',
                tribute_recipient_name = '',
                tribute_recipient_salutation = '',
                tribute_recipient_email = '',
                tribute_recipient_address = '',
                tribute_recipient_notification_template = '',
                team_member = '',
                custom_fields = [
                    lgl_openapi_3_0_client.models.custom_field_aggregated_update.CustomFieldAggregatedUpdate(
                        id = 56, 
                        name = '', 
                        key = '', 
                        remove_previous_values = True, 
                        values = [
                            lgl_openapi_3_0_client.models.custom_value_aggregated_update.CustomValueAggregatedUpdate(
                                id = 56, 
                                name = '', )
                            ], )
                    ]
            )
        else:
            return GiftUpdate(
                gift_type_id = 56,
                gift_type_name = '',
        )
        """

    def testGiftUpdate(self):
        """Test GiftUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
