# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.api.group_memberships_api import GroupMembershipsApi


class TestGroupMembershipsApi(unittest.TestCase):
    """GroupMembershipsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GroupMembershipsApi()

    def tearDown(self) -> None:
        pass

    def test_lgl_api_v1_group_memberships_create(self) -> None:
        """Test case for lgl_api_v1_group_memberships_create

        Create new Group Membership
        """
        pass

    def test_lgl_api_v1_group_memberships_destroy(self) -> None:
        """Test case for lgl_api_v1_group_memberships_destroy

        Delete Group Membership
        """
        pass

    def test_lgl_api_v1_group_memberships_update(self) -> None:
        """Test case for lgl_api_v1_group_memberships_update

        Update Group Membership
        """
        pass

    def test_v1_constituent_group_memberships(self) -> None:
        """Test case for v1_constituent_group_memberships

        Fetch Group Memberships
        """
        pass

    def test_v1_group_membership(self) -> None:
        """Test case for v1_group_membership

        Show Group Membership details
        """
        pass


if __name__ == '__main__':
    unittest.main()
