# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.api.gift_types_api import GiftTypesApi


class TestGiftTypesApi(unittest.TestCase):
    """GiftTypesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GiftTypesApi()

    def tearDown(self) -> None:
        pass

    def test_v1_gift_types(self) -> None:
        """Test case for v1_gift_types

        Fetch Gift Types
        """
        pass


if __name__ == '__main__':
    unittest.main()
