# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.models.constituent_relationships_show import ConstituentRelationshipsShow

class TestConstituentRelationshipsShow(unittest.TestCase):
    """ConstituentRelationshipsShow unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConstituentRelationshipsShow:
        """Test ConstituentRelationshipsShow
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConstituentRelationshipsShow`
        """
        model = ConstituentRelationshipsShow()
        if include_optional:
            return ConstituentRelationshipsShow(
                api_version = '',
                id = 56,
                relationship_type_id = 56,
                constituent_id = 56,
                related_constituent_id = 56,
                name = '',
                description = '',
                auto_soft_credit = True,
                also_acknowledge = True,
                share_address = 56,
                share_phone = 56
            )
        else:
            return ConstituentRelationshipsShow(
                api_version = '',
                id = 56,
        )
        """

    def testConstituentRelationshipsShow(self):
        """Test ConstituentRelationshipsShow"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
