# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.models.relationship_type_response import RelationshipTypeResponse

class TestRelationshipTypeResponse(unittest.TestCase):
    """RelationshipTypeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RelationshipTypeResponse:
        """Test RelationshipTypeResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RelationshipTypeResponse`
        """
        model = RelationshipTypeResponse()
        if include_optional:
            return RelationshipTypeResponse(
                id = 56,
                name = '',
                short_code = '',
                type_code = '',
                ordinal = 56,
                reciprocal_id = 56,
                auto_soft_credit = 56,
                is_spouse_partner = True
            )
        else:
            return RelationshipTypeResponse(
                id = 56,
                name = '',
        )
        """

    def testRelationshipTypeResponse(self):
        """Test RelationshipTypeResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
