# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.models.custom_value import CustomValue

class TestCustomValue(unittest.TestCase):
    """CustomValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomValue:
        """Test CustomValue
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomValue`
        """
        model = CustomValue()
        if include_optional:
            return CustomValue(
                category_id = 56,
                name = '',
                description = '',
                short_code = '',
                ordinal = 56,
                removable = True,
                can_change = True,
                can_select = True
            )
        else:
            return CustomValue(
                category_id = 56,
                name = '',
        )
        """

    def testCustomValue(self):
        """Test CustomValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
