# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.models.payment_types_show import PaymentTypesShow

class TestPaymentTypesShow(unittest.TestCase):
    """PaymentTypesShow unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentTypesShow:
        """Test PaymentTypesShow
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentTypesShow`
        """
        model = PaymentTypesShow()
        if include_optional:
            return PaymentTypesShow(
                api_version = '',
                id = 56,
                name = '',
                key = 1.337,
                ordinal = 56
            )
        else:
            return PaymentTypesShow(
                api_version = '',
                id = 56,
                name = '',
        )
        """

    def testPaymentTypesShow(self):
        """Test PaymentTypesShow"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
