# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.models.team_members_index import TeamMembersIndex

class TestTeamMembersIndex(unittest.TestCase):
    """TeamMembersIndex unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TeamMembersIndex:
        """Test TeamMembersIndex
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TeamMembersIndex`
        """
        model = TeamMembersIndex()
        if include_optional:
            return TeamMembersIndex(
                api_version = '',
                items_count = 56,
                total_items = 56,
                limit = 56,
                offset = 56,
                next_item = 56,
                next_link = '',
                item_type = '',
                items = [
                    lgl_openapi_3_0_client.models.team_member_response.TeamMemberResponse(
                        id = 56, 
                        first_name = '', 
                        last_name = '', 
                        email = '', 
                        role_id = 56, 
                        is_primary_contact = True, 
                        is_billing_contact = True, )
                    ]
            )
        else:
            return TeamMembersIndex(
                api_version = '',
                items_count = 56,
                total_items = 56,
                limit = 56,
                offset = 56,
                next_item = 56,
                next_link = '',
                item_type = '',
                items = [
                    lgl_openapi_3_0_client.models.team_member_response.TeamMemberResponse(
                        id = 56, 
                        first_name = '', 
                        last_name = '', 
                        email = '', 
                        role_id = 56, 
                        is_primary_contact = True, 
                        is_billing_contact = True, )
                    ],
        )
        """

    def testTeamMembersIndex(self):
        """Test TeamMembersIndex"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
