# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.models.street_address_update import StreetAddressUpdate

class TestStreetAddressUpdate(unittest.TestCase):
    """StreetAddressUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StreetAddressUpdate:
        """Test StreetAddressUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StreetAddressUpdate`
        """
        model = StreetAddressUpdate()
        if include_optional:
            return StreetAddressUpdate(
                id = 56,
                street = '',
                street_address_type_id = 56,
                street_type_name = '',
                city = '',
                state = '',
                postal_code = '',
                county = '',
                country = '',
                seasonal_from = '',
                seasonal_to = '',
                seasonal = True,
                is_preferred = True,
                not_current = True
            )
        else:
            return StreetAddressUpdate(
        )
        """

    def testStreetAddressUpdate(self):
        """Test StreetAddressUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
