# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.models.web_address_update import WebAddressUpdate

class TestWebAddressUpdate(unittest.TestCase):
    """WebAddressUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebAddressUpdate:
        """Test WebAddressUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebAddressUpdate`
        """
        model = WebAddressUpdate()
        if include_optional:
            return WebAddressUpdate(
                id = 56,
                url = '',
                web_address_type_id = 56,
                web_address_type_name = '',
                is_preferred = True
            )
        else:
            return WebAddressUpdate(
        )
        """

    def testWebAddressUpdate(self):
        """Test WebAddressUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
