# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.models.create_body_const import CreateBodyConst

class TestCreateBodyConst(unittest.TestCase):
    """CreateBodyConst unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateBodyConst:
        """Test CreateBodyConst
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateBodyConst`
        """
        model = CreateBodyConst()
        if include_optional:
            return CreateBodyConst(
                event_id = 56,
                parent_invitation_id = 56,
                notes = '',
                rsvp = 56,
                attended = 56,
                assigned_to = 56,
                attendee_names = '',
                guest_first_name = '',
                guest_last_name = '',
                is_a_guest = True,
                attendances = [
                    lgl_openapi_3_0_client.models.attendance_create.Attendance_create(
                        date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        notes = '', )
                    ],
                custom_fields = [
                    lgl_openapi_3_0_client.models.custom_field_aggregated_update.CustomFieldAggregatedUpdate(
                        id = 56, 
                        name = '', 
                        key = '', 
                        remove_previous_values = True, 
                        values = [
                            lgl_openapi_3_0_client.models.custom_value_aggregated_update.CustomValueAggregatedUpdate(
                                id = 56, 
                                name = '', )
                            ], )
                    ],
                custom_attrs = [
                    lgl_openapi_3_0_client.models.custom_attr_create.CustomAttr_create(
                        id = 56, 
                        key = '', 
                        value = '', )
                    ]
            )
        else:
            return CreateBodyConst(
                event_id = 56,
        )
        """

    def testCreateBodyConst(self):
        """Test CreateBodyConst"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
