# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.models.email_address_update import EmailAddressUpdate

class TestEmailAddressUpdate(unittest.TestCase):
    """EmailAddressUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EmailAddressUpdate:
        """Test EmailAddressUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EmailAddressUpdate`
        """
        model = EmailAddressUpdate()
        if include_optional:
            return EmailAddressUpdate(
                id = 56,
                address = '',
                email_address_type_id = 56,
                email_type_name = '',
                is_preferred = True,
                not_current = True
            )
        else:
            return EmailAddressUpdate(
        )
        """

    def testEmailAddressUpdate(self):
        """Test EmailAddressUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
