# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.api.email_addresses_api import EmailAddressesApi


class TestEmailAddressesApi(unittest.TestCase):
    """EmailAddressesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EmailAddressesApi()

    def tearDown(self) -> None:
        pass

    def test_lgl_api_v1_email_addresses_create(self) -> None:
        """Test case for lgl_api_v1_email_addresses_create

        Create new Email Address
        """
        pass

    def test_lgl_api_v1_email_addresses_destroy(self) -> None:
        """Test case for lgl_api_v1_email_addresses_destroy

        Delete Email Address
        """
        pass

    def test_lgl_api_v1_email_addresses_update(self) -> None:
        """Test case for lgl_api_v1_email_addresses_update

        Update Email Address
        """
        pass

    def test_v1_constituent_email_addresses(self) -> None:
        """Test case for v1_constituent_email_addresses

        Fetch Email Addresses
        """
        pass

    def test_v1_email_address(self) -> None:
        """Test case for v1_email_address

        Show Email Address details
        """
        pass


if __name__ == '__main__':
    unittest.main()
