# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.api.phone_numbers_api import PhoneNumbersApi


class TestPhoneNumbersApi(unittest.TestCase):
    """PhoneNumbersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PhoneNumbersApi()

    def tearDown(self) -> None:
        pass

    def test_lgl_api_v1_phone_numbers_create(self) -> None:
        """Test case for lgl_api_v1_phone_numbers_create

        Create new Phone Number
        """
        pass

    def test_lgl_api_v1_phone_numbers_destroy(self) -> None:
        """Test case for lgl_api_v1_phone_numbers_destroy

        Delete Phone Number
        """
        pass

    def test_lgl_api_v1_phone_numbers_update(self) -> None:
        """Test case for lgl_api_v1_phone_numbers_update

        Update Phone Number
        """
        pass

    def test_v1_constituent_phone_numbers(self) -> None:
        """Test case for v1_constituent_phone_numbers

        Fetch Phone Numbers
        """
        pass

    def test_v1_phone_number(self) -> None:
        """Test case for v1_phone_number

        Show Phone Number details
        """
        pass


if __name__ == '__main__':
    unittest.main()
