# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.models.school_aggregated_response import SchoolAggregatedResponse

class TestSchoolAggregatedResponse(unittest.TestCase):
    """SchoolAggregatedResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SchoolAggregatedResponse:
        """Test SchoolAggregatedResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SchoolAggregatedResponse`
        """
        model = SchoolAggregatedResponse()
        if include_optional:
            return SchoolAggregatedResponse(
                id = 56,
                school_name = '',
                school_type_id = 56,
                year = '',
                degree = '',
                specialization = '',
                add_class_year = True,
                school_tie_type_id = 56
            )
        else:
            return SchoolAggregatedResponse(
                id = 56,
        )
        """

    def testSchoolAggregatedResponse(self):
        """Test SchoolAggregatedResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
