# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.models.appeal_request_aggregated_response import AppealRequestAggregatedResponse

class TestAppealRequestAggregatedResponse(unittest.TestCase):
    """AppealRequestAggregatedResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppealRequestAggregatedResponse:
        """Test AppealRequestAggregatedResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppealRequestAggregatedResponse`
        """
        model = AppealRequestAggregatedResponse()
        if include_optional:
            return AppealRequestAggregatedResponse(
                id = 56,
                constituent_id = 56,
                appeal_id = 56,
                ask_amount = 1.337,
                status = '',
                assigned_to = 56,
                custom_fields = [
                    lgl_openapi_3_0_client.models.custom_field_aggregated_update.CustomFieldAggregatedUpdate(
                        id = 56, 
                        name = '', 
                        key = '', 
                        remove_previous_values = True, 
                        values = [
                            lgl_openapi_3_0_client.models.custom_value_aggregated_update.CustomValueAggregatedUpdate(
                                id = 56, 
                                name = '', )
                            ], )
                    ],
                custom_attrs = [
                    lgl_openapi_3_0_client.models.custom_attr_create.CustomAttr_create(
                        id = 56, 
                        key = '', 
                        value = '', )
                    ]
            )
        else:
            return AppealRequestAggregatedResponse(
                id = 56,
                constituent_id = 56,
                appeal_id = 56,
        )
        """

    def testAppealRequestAggregatedResponse(self):
        """Test AppealRequestAggregatedResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
