# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.models.custom_field import CustomField

class TestCustomField(unittest.TestCase):
    """CustomField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomField:
        """Test CustomField
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomField`
        """
        model = CustomField()
        if include_optional:
            return CustomField(
                id = 56,
                item_type = '',
                name = '',
                key = '',
                facet_type = '',
                ordinal = 56,
                removable = True,
                editable = True,
                values = [
                    lgl_openapi_3_0_client.models.custom_value.CustomValue(
                        category_id = 56, 
                        name = '', 
                        description = '', 
                        short_code = '', 
                        ordinal = 56, 
                        removable = True, 
                        can_change = True, 
                        can_select = True, )
                    ]
            )
        else:
            return CustomField(
                item_type = '',
                name = '',
                values = [
                    lgl_openapi_3_0_client.models.custom_value.CustomValue(
                        category_id = 56, 
                        name = '', 
                        description = '', 
                        short_code = '', 
                        ordinal = 56, 
                        removable = True, 
                        can_change = True, 
                        can_select = True, )
                    ],
        )
        """

    def testCustomField(self):
        """Test CustomField"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
