# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.models.volunteer_time import VolunteerTime

class TestVolunteerTime(unittest.TestCase):
    """VolunteerTime unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VolunteerTime:
        """Test VolunteerTime
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VolunteerTime`
        """
        model = VolunteerTime()
        if include_optional:
            return VolunteerTime(
                constituent_id = 56,
                external_id = 56,
                volunteering_category_id = 56,
                volunteering_category_name = '',
                description = '',
                hours = 1.337,
                var_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                end_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                completed_hours = 1.337,
                custom_fields = [
                    lgl_openapi_3_0_client.models.custom_field_aggregated_update.CustomFieldAggregatedUpdate(
                        id = 56, 
                        name = '', 
                        key = '', 
                        remove_previous_values = True, 
                        values = [
                            lgl_openapi_3_0_client.models.custom_value_aggregated_update.CustomValueAggregatedUpdate(
                                id = 56, 
                                name = '', )
                            ], )
                    ]
            )
        else:
            return VolunteerTime(
                constituent_id = 56,
                volunteering_category_id = 56,
        )
        """

    def testVolunteerTime(self):
        """Test VolunteerTime"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
