# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.models.volunteer_times_index import VolunteerTimesIndex

class TestVolunteerTimesIndex(unittest.TestCase):
    """VolunteerTimesIndex unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VolunteerTimesIndex:
        """Test VolunteerTimesIndex
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VolunteerTimesIndex`
        """
        model = VolunteerTimesIndex()
        if include_optional:
            return VolunteerTimesIndex(
                api_version = '',
                items_count = 56,
                total_items = 56,
                limit = 56,
                offset = 56,
                next_item = 56,
                next_link = '',
                item_type = '',
                items = [
                    lgl_openapi_3_0_client.models.volunteer_time_response.VolunteerTimeResponse(
                        id = 56, 
                        constituent_id = 56, 
                        external_id = 56, 
                        volunteering_category_id = 56, 
                        volunteering_category_name = '', 
                        description = '', 
                        hours = 1.337, 
                        date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        end_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        completed_hours = 1.337, 
                        custom_fields = [
                            lgl_openapi_3_0_client.models.custom_field.CustomField(
                                id = 56, 
                                item_type = '', 
                                name = '', 
                                key = '', 
                                facet_type = '', 
                                ordinal = 56, 
                                removable = True, 
                                editable = True, 
                                values = [
                                    lgl_openapi_3_0_client.models.custom_value.CustomValue(
                                        category_id = 56, 
                                        name = '', 
                                        description = '', 
                                        short_code = '', 
                                        ordinal = 56, 
                                        removable = True, 
                                        can_change = True, 
                                        can_select = True, )
                                    ], )
                            ], 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return VolunteerTimesIndex(
                api_version = '',
                items_count = 56,
                total_items = 56,
                limit = 56,
                offset = 56,
                next_item = 56,
                next_link = '',
                item_type = '',
                items = [
                    lgl_openapi_3_0_client.models.volunteer_time_response.VolunteerTimeResponse(
                        id = 56, 
                        constituent_id = 56, 
                        external_id = 56, 
                        volunteering_category_id = 56, 
                        volunteering_category_name = '', 
                        description = '', 
                        hours = 1.337, 
                        date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        end_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        completed_hours = 1.337, 
                        custom_fields = [
                            lgl_openapi_3_0_client.models.custom_field.CustomField(
                                id = 56, 
                                item_type = '', 
                                name = '', 
                                key = '', 
                                facet_type = '', 
                                ordinal = 56, 
                                removable = True, 
                                editable = True, 
                                values = [
                                    lgl_openapi_3_0_client.models.custom_value.CustomValue(
                                        category_id = 56, 
                                        name = '', 
                                        description = '', 
                                        short_code = '', 
                                        ordinal = 56, 
                                        removable = True, 
                                        can_change = True, 
                                        can_select = True, )
                                    ], )
                            ], 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
        )
        """

    def testVolunteerTimesIndex(self):
        """Test VolunteerTimesIndex"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
