# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.api.types_api import TypesApi


class TestTypesApi(unittest.TestCase):
    """TypesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TypesApi()

    def tearDown(self) -> None:
        pass

    def test_v1_types(self) -> None:
        """Test case for v1_types

        Fetch Types for Account
        """
        pass

    def test_v1_v1_types_type(self) -> None:
        """Test case for v1_v1_types_type

        Fetch Values for Type
        """
        pass


if __name__ == '__main__':
    unittest.main()
