# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.models.custom_value_update import CustomValueUpdate

class TestCustomValueUpdate(unittest.TestCase):
    """CustomValueUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomValueUpdate:
        """Test CustomValueUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomValueUpdate`
        """
        model = CustomValueUpdate()
        if include_optional:
            return CustomValueUpdate(
                id = 56,
                category_id = 56,
                name = '',
                description = '',
                short_code = '',
                ordinal = 56,
                removable = True,
                can_change = True,
                can_select = True
            )
        else:
            return CustomValueUpdate(
                category_id = 56,
                name = '',
        )
        """

    def testCustomValueUpdate(self):
        """Test CustomValueUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
