# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.models.events_index import EventsIndex

class TestEventsIndex(unittest.TestCase):
    """EventsIndex unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EventsIndex:
        """Test EventsIndex
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EventsIndex`
        """
        model = EventsIndex()
        if include_optional:
            return EventsIndex(
                api_version = '',
                items_count = 56,
                total_items = 56,
                limit = 56,
                offset = 56,
                next_item = 56,
                next_link = '',
                item_type = '',
                items = [
                    lgl_openapi_3_0_client.models.event_response.EventResponse(
                        id = 56, 
                        name = '', 
                        description = '', 
                        date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        end_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        financial_goal = 1.337, 
                        projected_amount = 1.337, 
                        code = '', )
                    ]
            )
        else:
            return EventsIndex(
                api_version = '',
                items_count = 56,
                total_items = 56,
                limit = 56,
                offset = 56,
                next_item = 56,
                next_link = '',
                item_type = '',
                items = [
                    lgl_openapi_3_0_client.models.event_response.EventResponse(
                        id = 56, 
                        name = '', 
                        description = '', 
                        date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        end_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        financial_goal = 1.337, 
                        projected_amount = 1.337, 
                        code = '', )
                    ],
        )
        """

    def testEventsIndex(self):
        """Test EventsIndex"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
