# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.api.relationship_types_api import RelationshipTypesApi


class TestRelationshipTypesApi(unittest.TestCase):
    """RelationshipTypesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RelationshipTypesApi()

    def tearDown(self) -> None:
        pass

    def test_v1_relationship_types(self) -> None:
        """Test case for v1_relationship_types

        Fetch Relationship Types
        """
        pass


if __name__ == '__main__':
    unittest.main()
