# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.models.volunteer_time_response import VolunteerTimeResponse

class TestVolunteerTimeResponse(unittest.TestCase):
    """VolunteerTimeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VolunteerTimeResponse:
        """Test VolunteerTimeResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VolunteerTimeResponse`
        """
        model = VolunteerTimeResponse()
        if include_optional:
            return VolunteerTimeResponse(
                id = 56,
                constituent_id = 56,
                external_id = 56,
                volunteering_category_id = 56,
                volunteering_category_name = '',
                description = '',
                hours = 1.337,
                var_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                end_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                completed_hours = 1.337,
                custom_fields = [
                    lgl_openapi_3_0_client.models.custom_field.CustomField(
                        id = 56, 
                        item_type = '', 
                        name = '', 
                        key = '', 
                        facet_type = '', 
                        ordinal = 56, 
                        removable = True, 
                        editable = True, 
                        values = [
                            lgl_openapi_3_0_client.models.custom_value.CustomValue(
                                category_id = 56, 
                                name = '', 
                                description = '', 
                                short_code = '', 
                                ordinal = 56, 
                                removable = True, 
                                can_change = True, 
                                can_select = True, )
                            ], )
                    ],
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return VolunteerTimeResponse(
                id = 56,
                constituent_id = 56,
                volunteering_category_id = 56,
        )
        """

    def testVolunteerTimeResponse(self):
        """Test VolunteerTimeResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
