# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.models.category_aggregated_update import CategoryAggregatedUpdate

class TestCategoryAggregatedUpdate(unittest.TestCase):
    """CategoryAggregatedUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CategoryAggregatedUpdate:
        """Test CategoryAggregatedUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CategoryAggregatedUpdate`
        """
        model = CategoryAggregatedUpdate()
        if include_optional:
            return CategoryAggregatedUpdate(
                id = 56,
                name = '',
                key = '',
                remove_previous_keywords = True,
                keywords = [
                    lgl_openapi_3_0_client.models.keyword_aggregated_update.KeywordAggregatedUpdate(
                        id = 56, 
                        name = '', 
                        short_code = '', )
                    ]
            )
        else:
            return CategoryAggregatedUpdate(
                name = '',
                keywords = [
                    lgl_openapi_3_0_client.models.keyword_aggregated_update.KeywordAggregatedUpdate(
                        id = 56, 
                        name = '', 
                        short_code = '', )
                    ],
        )
        """

    def testCategoryAggregatedUpdate(self):
        """Test CategoryAggregatedUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
