# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.api.contact_reports_api import ContactReportsApi


class TestContactReportsApi(unittest.TestCase):
    """ContactReportsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ContactReportsApi()

    def tearDown(self) -> None:
        pass

    def test_lgl_api_v1_contact_reports_create(self) -> None:
        """Test case for lgl_api_v1_contact_reports_create

        Create new Contact Report
        """
        pass

    def test_lgl_api_v1_contact_reports_destroy(self) -> None:
        """Test case for lgl_api_v1_contact_reports_destroy

        Delete Contact Report
        """
        pass

    def test_lgl_api_v1_contact_reports_update(self) -> None:
        """Test case for lgl_api_v1_contact_reports_update

        Update Contact Report
        """
        pass

    def test_search_v1_contact_reports(self) -> None:
        """Test case for search_v1_contact_reports

        Search for Contact Reports
        """
        pass

    def test_v1_constituent_contact_reports(self) -> None:
        """Test case for v1_constituent_contact_reports

        Fetch Contact Reports for Constituent
        """
        pass

    def test_v1_contact_report(self) -> None:
        """Test case for v1_contact_report

        Show Contact Report details
        """
        pass

    def test_v1_contact_reports(self) -> None:
        """Test case for v1_contact_reports

        Fetch Contact Reports for Account
        """
        pass


if __name__ == '__main__':
    unittest.main()
