# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.api.notes_api import NotesApi


class TestNotesApi(unittest.TestCase):
    """NotesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NotesApi()

    def tearDown(self) -> None:
        pass

    def test_lgl_api_v1_notes_create(self) -> None:
        """Test case for lgl_api_v1_notes_create

        Create new Note
        """
        pass

    def test_lgl_api_v1_notes_destroy(self) -> None:
        """Test case for lgl_api_v1_notes_destroy

        Delete Note
        """
        pass

    def test_lgl_api_v1_notes_update(self) -> None:
        """Test case for lgl_api_v1_notes_update

        Update Note
        """
        pass

    def test_v1_constituent_notes(self) -> None:
        """Test case for v1_constituent_notes

        Fetch Notes for Constituent
        """
        pass

    def test_v1_note(self) -> None:
        """Test case for v1_note

        Show Note details
        """
        pass

    def test_v1_notes(self) -> None:
        """Test case for v1_notes

        Fetch Notes for Account
        """
        pass


if __name__ == '__main__':
    unittest.main()
