# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.api.appeal_requests_api import AppealRequestsApi


class TestAppealRequestsApi(unittest.TestCase):
    """AppealRequestsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AppealRequestsApi()

    def tearDown(self) -> None:
        pass

    def test_lgl_api_v1_appeal_requests_create(self) -> None:
        """Test case for lgl_api_v1_appeal_requests_create

        Create new Appeal Request
        """
        pass

    def test_lgl_api_v1_appeal_requests_destroy(self) -> None:
        """Test case for lgl_api_v1_appeal_requests_destroy

        Delete Appeal Request
        """
        pass

    def test_lgl_api_v1_appeal_requests_update(self) -> None:
        """Test case for lgl_api_v1_appeal_requests_update

        Update Appeal Request
        """
        pass

    def test_v1_appeal_appeal_requests(self) -> None:
        """Test case for v1_appeal_appeal_requests

        Fetch Appeal Requests for Appeal
        """
        pass

    def test_v1_appeal_request(self) -> None:
        """Test case for v1_appeal_request

        Show Appeal Request details
        """
        pass

    def test_v1_constituent_appeal_requests(self) -> None:
        """Test case for v1_constituent_appeal_requests

        Fetch Appeal Requests for Constituent
        """
        pass

    def test_v1_create_appeal_request_v1_constituent_appeal_requests(self) -> None:
        """Test case for v1_create_appeal_request_v1_constituent_appeal_requests

        Create new Appeal Request for Constituent
        """
        pass


if __name__ == '__main__':
    unittest.main()
