# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.api.campaigns_api import CampaignsApi


class TestCampaignsApi(unittest.TestCase):
    """CampaignsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CampaignsApi()

    def tearDown(self) -> None:
        pass

    def test_v1_campaigns(self) -> None:
        """Test case for v1_campaigns

        Fetch Campaigns
        """
        pass


if __name__ == '__main__':
    unittest.main()
