# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.api.mailing_templates_api import MailingTemplatesApi


class TestMailingTemplatesApi(unittest.TestCase):
    """MailingTemplatesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MailingTemplatesApi()

    def tearDown(self) -> None:
        pass

    def test_v1_mailing_templates(self) -> None:
        """Test case for v1_mailing_templates

        Fetch Mailing Templates
        """
        pass


if __name__ == '__main__':
    unittest.main()
