# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.api.groups_api import GroupsApi


class TestGroupsApi(unittest.TestCase):
    """GroupsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GroupsApi()

    def tearDown(self) -> None:
        pass

    def test_lgl_api_v1_groups_create(self) -> None:
        """Test case for lgl_api_v1_groups_create

        Create new Group
        """
        pass

    def test_lgl_api_v1_groups_destroy(self) -> None:
        """Test case for lgl_api_v1_groups_destroy

        Delete Group
        """
        pass

    def test_lgl_api_v1_groups_update(self) -> None:
        """Test case for lgl_api_v1_groups_update

        Update Group
        """
        pass

    def test_v1_group(self) -> None:
        """Test case for v1_group

        Show Group details
        """
        pass

    def test_v1_groups(self) -> None:
        """Test case for v1_groups

        Fetch Groups
        """
        pass


if __name__ == '__main__':
    unittest.main()
