# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.models.contact_report import ContactReport

class TestContactReport(unittest.TestCase):
    """ContactReport unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContactReport:
        """Test ContactReport
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContactReport`
        """
        model = ContactReport()
        if include_optional:
            return ContactReport(
                name = '',
                contact_report_type_id = 56,
                contact_report_type_name = '',
                original_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                text = '',
                team_member = ''
            )
        else:
            return ContactReport(
                text = '',
        )
        """

    def testContactReport(self):
        """Test ContactReport"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
