# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.models.keyword_response import KeywordResponse

class TestKeywordResponse(unittest.TestCase):
    """KeywordResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> KeywordResponse:
        """Test KeywordResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `KeywordResponse`
        """
        model = KeywordResponse()
        if include_optional:
            return KeywordResponse(
                id = 56,
                category_id = 56,
                name = '',
                description = '',
                short_code = '',
                ordinal = 56,
                removable = True,
                can_change = True,
                can_select = True,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return KeywordResponse(
                id = 56,
                category_id = 56,
                name = '',
        )
        """

    def testKeywordResponse(self):
        """Test KeywordResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
