# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.models.email_addresses_show import EmailAddressesShow

class TestEmailAddressesShow(unittest.TestCase):
    """EmailAddressesShow unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EmailAddressesShow:
        """Test EmailAddressesShow
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EmailAddressesShow`
        """
        model = EmailAddressesShow()
        if include_optional:
            return EmailAddressesShow(
                api_version = '',
                id = 56,
                item_id = 56,
                item_type = '',
                address = '',
                email_address_type_id = 56,
                email_type_name = '',
                is_preferred = True,
                not_current = True,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return EmailAddressesShow(
                api_version = '',
                id = 56,
                item_id = 56,
                item_type = '',
        )
        """

    def testEmailAddressesShow(self):
        """Test EmailAddressesShow"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
