# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.models.appeal_response import AppealResponse

class TestAppealResponse(unittest.TestCase):
    """AppealResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppealResponse:
        """Test AppealResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppealResponse`
        """
        model = AppealResponse()
        if include_optional:
            return AppealResponse(
                id = 56,
                name = '',
                description = '',
                var_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                financial_goal = 1.337,
                projected_amount = 1.337,
                code = '',
                is_active = True
            )
        else:
            return AppealResponse(
                id = 56,
                name = '',
        )
        """

    def testAppealResponse(self):
        """Test AppealResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
