# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.models.street_address_aggregated_response import StreetAddressAggregatedResponse

class TestStreetAddressAggregatedResponse(unittest.TestCase):
    """StreetAddressAggregatedResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StreetAddressAggregatedResponse:
        """Test StreetAddressAggregatedResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StreetAddressAggregatedResponse`
        """
        model = StreetAddressAggregatedResponse()
        if include_optional:
            return StreetAddressAggregatedResponse(
                id = 56,
                street = '',
                city = '',
                state = '',
                country = '',
                postal_code = '',
                county = '',
                street_address_type_id = 56,
                street_type_name = '',
                is_preferred = True,
                not_current = True,
                seasonal_from = '',
                seasonal_to = '',
                seasonal = True,
                lat = 1.337,
                lng = 1.337,
                zip5 = '',
                verified = True,
                verified_on = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return StreetAddressAggregatedResponse(
                id = 56,
        )
        """

    def testStreetAddressAggregatedResponse(self):
        """Test StreetAddressAggregatedResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
