# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.models.attributes_index import AttributesIndex

class TestAttributesIndex(unittest.TestCase):
    """AttributesIndex unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AttributesIndex:
        """Test AttributesIndex
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AttributesIndex`
        """
        model = AttributesIndex()
        if include_optional:
            return AttributesIndex(
                api_version = '',
                items_count = 56,
                total_items = 56,
                limit = 56,
                offset = 56,
                next_item = 56,
                next_link = '',
                item_type = '',
                items = [
                    lgl_openapi_3_0_client.models.attribute_response.AttributeResponse(
                        id = 56, 
                        item_type = 56, 
                        name = '', 
                        description = '', 
                        key = '', 
                        min_val = 56, 
                        max_val = 56, )
                    ]
            )
        else:
            return AttributesIndex(
                api_version = '',
                items_count = 56,
                total_items = 56,
                limit = 56,
                offset = 56,
                next_item = 56,
                next_link = '',
                item_type = '',
                items = [
                    lgl_openapi_3_0_client.models.attribute_response.AttributeResponse(
                        id = 56, 
                        item_type = 56, 
                        name = '', 
                        description = '', 
                        key = '', 
                        min_val = 56, 
                        max_val = 56, )
                    ],
        )
        """

    def testAttributesIndex(self):
        """Test AttributesIndex"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
