# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.models.contact_reports_show import ContactReportsShow

class TestContactReportsShow(unittest.TestCase):
    """ContactReportsShow unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContactReportsShow:
        """Test ContactReportsShow
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContactReportsShow`
        """
        model = ContactReportsShow()
        if include_optional:
            return ContactReportsShow(
                api_version = '',
                id = 56,
                constituent_id = 56,
                name = '',
                contact_report_type_id = 56,
                contact_report_type_name = '',
                original_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                text = '',
                team_member = '',
                team_member_email = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return ContactReportsShow(
                api_version = '',
                id = 56,
                constituent_id = 56,
                text = '',
        )
        """

    def testContactReportsShow(self):
        """Test ContactReportsShow"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
