# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.api.invitations_api import InvitationsApi


class TestInvitationsApi(unittest.TestCase):
    """InvitationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InvitationsApi()

    def tearDown(self) -> None:
        pass

    def test_lgl_api_v1_invitations_create(self) -> None:
        """Test case for lgl_api_v1_invitations_create

        Create new Invitation
        """
        pass

    def test_lgl_api_v1_invitations_destroy(self) -> None:
        """Test case for lgl_api_v1_invitations_destroy

        Delete Invitation
        """
        pass

    def test_lgl_api_v1_invitations_update(self) -> None:
        """Test case for lgl_api_v1_invitations_update

        Update Invitation
        """
        pass

    def test_v1_constituent_invitations(self) -> None:
        """Test case for v1_constituent_invitations

        Fetch Invitations for Constituent
        """
        pass

    def test_v1_create_invitation_v1_constituent_invitations(self) -> None:
        """Test case for v1_create_invitation_v1_constituent_invitations

        Create new Invitation for Constituent
        """
        pass

    def test_v1_event_invitations(self) -> None:
        """Test case for v1_event_invitations

        Fetch Invitations for Event
        """
        pass

    def test_v1_invitation(self) -> None:
        """Test case for v1_invitation

        Show Invitation details
        """
        pass


if __name__ == '__main__':
    unittest.main()
