# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgl_openapi_3_0_client.models.constituent_update import ConstituentUpdate

class TestConstituentUpdate(unittest.TestCase):
    """ConstituentUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConstituentUpdate:
        """Test ConstituentUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConstituentUpdate`
        """
        model = ConstituentUpdate()
        if include_optional:
            return ConstituentUpdate(
                id = 56,
                external_constituent_id = 56,
                is_org = True,
                constituent_contact_type_id = 56,
                constituent_contact_type_name = '',
                prefix = '',
                first_name = '',
                middle_name = '',
                last_name = '',
                suffix = '',
                spouse_name = '',
                org_name = '',
                job_title = '',
                addressee = '',
                salutation = '',
                is_deceased = True,
                deceased_date = '',
                annual_report_name = '',
                birthday = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                gender = '',
                maiden_name = '',
                nick_name = '',
                spouse_nick_name = '',
                date_added = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                alt_salutation = '',
                alt_addressee = '',
                honorary_name = '',
                assistant_name = '',
                marital_status_id = 56,
                marital_status_name = '',
                is_anon = True
            )
        else:
            return ConstituentUpdate(
                first_name = '',
                last_name = '',
        )
        """

    def testConstituentUpdate(self):
        """Test ConstituentUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
