# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from lgl_openapi_3_0_client.models.custom_attr import CustomAttr
from lgl_openapi_3_0_client.models.custom_field import CustomField
from typing import Optional, Set
from typing_extensions import Self

class AppealRequestResponse(BaseModel):
    """
    A AppealRequest object.
    """ # noqa: E501
    id: StrictInt = Field(description="Appeal Request Id")
    constituent_id: StrictInt = Field(description="Constituent Id")
    constituent_name: Optional[StrictStr] = Field(default=None, description="Constituent Name")
    appeal_id: StrictInt = Field(description="Appeal Id")
    name: Optional[StrictStr] = Field(default=None, description="Appeal Name")
    raised: Optional[Union[StrictFloat, StrictInt]] = None
    status: Optional[StrictStr] = Field(default=None, description="Status")
    ask_amount: Optional[Union[StrictFloat, StrictInt]] = None
    assigned_to: Optional[StrictInt] = Field(default=None, description="Assigned to team member id")
    custom_fields: Optional[List[CustomField]] = Field(default=None, description="Appeal request custom fields (Categories)")
    custom_attrs: Optional[List[CustomAttr]] = Field(default=None, description="Appeal request custom attributes")
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["id", "constituent_id", "constituent_name", "appeal_id", "name", "raised", "status", "ask_amount", "assigned_to", "custom_fields", "custom_attrs", "created_at", "updated_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AppealRequestResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in custom_fields (list)
        _items = []
        if self.custom_fields:
            for _item_custom_fields in self.custom_fields:
                if _item_custom_fields:
                    _items.append(_item_custom_fields.to_dict())
            _dict['custom_fields'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in custom_attrs (list)
        _items = []
        if self.custom_attrs:
            for _item_custom_attrs in self.custom_attrs:
                if _item_custom_attrs:
                    _items.append(_item_custom_attrs.to_dict())
            _dict['custom_attrs'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AppealRequestResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "constituent_id": obj.get("constituent_id"),
            "constituent_name": obj.get("constituent_name"),
            "appeal_id": obj.get("appeal_id"),
            "name": obj.get("name"),
            "raised": obj.get("raised"),
            "status": obj.get("status"),
            "ask_amount": obj.get("ask_amount"),
            "assigned_to": obj.get("assigned_to"),
            "custom_fields": [CustomField.from_dict(_item) for _item in obj["custom_fields"]] if obj.get("custom_fields") is not None else None,
            "custom_attrs": [CustomAttr.from_dict(_item) for _item in obj["custom_attrs"]] if obj.get("custom_attrs") is not None else None,
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


