# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from lgl_openapi_3_0_client.models.keyword_response import KeywordResponse
from typing import Optional, Set
from typing_extensions import Self

class Category(BaseModel):
    """
    A Category object.
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="Category Id")
    item_type: StrictStr = Field(description="Item Type")
    name: StrictStr = Field(description="Name")
    key: Optional[StrictStr] = Field(default=None, description="Key")
    facet_type: Optional[StrictStr] = Field(default=None, description="Facet Type")
    ordinal: Optional[StrictInt] = Field(default=None, description="Ordinal")
    removable: Optional[StrictBool] = Field(default=None, description="Removable?")
    editable: Optional[StrictBool] = Field(default=None, description="Editable?")
    display_format: Optional[StrictStr] = Field(default=None, description="Display Format")
    keywords: List[KeywordResponse] = Field(description="Keyword Values")
    __properties: ClassVar[List[str]] = ["id", "item_type", "name", "key", "facet_type", "ordinal", "removable", "editable", "display_format", "keywords"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Category from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in keywords (list)
        _items = []
        if self.keywords:
            for _item_keywords in self.keywords:
                if _item_keywords:
                    _items.append(_item_keywords.to_dict())
            _dict['keywords'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Category from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "item_type": obj.get("item_type"),
            "name": obj.get("name"),
            "key": obj.get("key"),
            "facet_type": obj.get("facet_type"),
            "ordinal": obj.get("ordinal"),
            "removable": obj.get("removable"),
            "editable": obj.get("editable"),
            "display_format": obj.get("display_format"),
            "keywords": [KeywordResponse.from_dict(_item) for _item in obj["keywords"]] if obj.get("keywords") is not None else None
        })
        return _obj


