# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ConstituentRelationshipUpdate(BaseModel):
    """
    A ConstituentRelationship object.
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="ConstituentRelationship ID")
    related_constituent_id: Optional[StrictInt] = Field(default=None, description="Related Constituent ID")
    relationship_type_id: Optional[StrictInt] = Field(default=None, description="Relationship Type ID")
    name: Optional[StrictStr] = Field(default=None, description="Relationship name")
    description: Optional[StrictStr] = Field(default=None, description="Relationship description")
    reciprocal_id: Optional[StrictInt] = Field(default=None, description="Reciprocal Relationship Type ID")
    rec_name: Optional[StrictStr] = Field(default=None, description="Reciprocal relationship name")
    reciprocal_description: Optional[StrictStr] = Field(default=None, description="Reciprocal relationship description")
    share_address: Optional[StrictInt] = Field(default=None, description="Share address?")
    share_phone: Optional[StrictInt] = Field(default=None, description="Share phone?")
    auto_soft_credit: Optional[StrictBool] = Field(default=None, description="Automatically soft credit?")
    also_acknowledge: Optional[StrictBool] = Field(default=None, description="Send memorial acknowledgements?")
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["id", "related_constituent_id", "relationship_type_id", "name", "description", "reciprocal_id", "rec_name", "reciprocal_description", "share_address", "share_phone", "auto_soft_credit", "also_acknowledge", "created_at", "updated_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConstituentRelationshipUpdate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConstituentRelationshipUpdate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "related_constituent_id": obj.get("related_constituent_id"),
            "relationship_type_id": obj.get("relationship_type_id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "reciprocal_id": obj.get("reciprocal_id"),
            "rec_name": obj.get("rec_name"),
            "reciprocal_description": obj.get("reciprocal_description"),
            "share_address": obj.get("share_address"),
            "share_phone": obj.get("share_phone"),
            "auto_soft_credit": obj.get("auto_soft_credit"),
            "also_acknowledge": obj.get("also_acknowledge"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


