# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date, datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ConstituentResponse(BaseModel):
    """
    A Constituent object.
    """ # noqa: E501
    id: StrictInt = Field(description="Constituent ID")
    external_constituent_id: Optional[StrictInt] = Field(default=None, description="External constituent ID")
    is_org: Optional[StrictBool] = Field(default=None, description="This constituent is an organization or company")
    constituent_contact_type_id: Optional[StrictInt] = Field(default=None, description="Constituent contact type ID")
    constituent_contact_type_name: Optional[StrictStr] = Field(default=None, description="Constituent contact type")
    prefix: Optional[StrictStr] = Field(default=None, description="Prefix")
    first_name: StrictStr = Field(description="First name")
    middle_name: Optional[StrictStr] = Field(default=None, description="Middle name")
    last_name: StrictStr = Field(description="Last name")
    suffix: Optional[StrictStr] = Field(default=None, description="Suffix")
    spouse_name: Optional[StrictStr] = Field(default=None, description="Spouse/Partner")
    org_name: Optional[StrictStr] = Field(default=None, description="Organization name")
    job_title: Optional[StrictStr] = Field(default=None, description="Job title")
    addressee: Optional[StrictStr] = Field(default=None, description="Addressee/Label name")
    salutation: Optional[StrictStr] = Field(default=None, description="Salutation")
    sort_name: Optional[StrictStr] = Field(default=None, description="Sort name")
    constituent_interest_level_id: Optional[StrictInt] = Field(default=None, description="Interest Level ID")
    constituent_interest_level_name: Optional[StrictStr] = Field(default=None, description="Interest Level")
    constituent_rating_id: Optional[StrictInt] = Field(default=None, description="Capacity ID")
    constituent_rating_name: Optional[StrictStr] = Field(default=None, description="Capacity")
    is_deceased: Optional[StrictBool] = Field(default=None, description="Deceased?")
    deceased_date: Optional[StrictStr] = Field(default=None, description="Deceased date")
    annual_report_name: Optional[StrictStr] = Field(default=None, description="Annual report name")
    birthday: Optional[date] = None
    gender: Optional[StrictStr] = Field(default=None, description="Gender")
    maiden_name: Optional[StrictStr] = Field(default=None, description="Maiden name")
    nick_name: Optional[StrictStr] = Field(default=None, description="Nickname")
    spouse_nick_name: Optional[StrictStr] = Field(default=None, description="Spouse nickname")
    date_added: Optional[date] = None
    alt_salutation: Optional[StrictStr] = Field(default=None, description="Alt salutation")
    alt_addressee: Optional[StrictStr] = Field(default=None, description="Alt addressee")
    honorary_name: Optional[StrictStr] = Field(default=None, description="Honorary name")
    assistant_name: Optional[StrictStr] = Field(default=None, description="Assistant name")
    marital_status_id: Optional[StrictInt] = Field(default=None, description="Marital status ID")
    marital_status_name: Optional[StrictStr] = Field(default=None, description="Marital status")
    is_anon: Optional[StrictBool] = Field(default=None, description="Gives anonymously?")
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["id", "external_constituent_id", "is_org", "constituent_contact_type_id", "constituent_contact_type_name", "prefix", "first_name", "middle_name", "last_name", "suffix", "spouse_name", "org_name", "job_title", "addressee", "salutation", "sort_name", "constituent_interest_level_id", "constituent_interest_level_name", "constituent_rating_id", "constituent_rating_name", "is_deceased", "deceased_date", "annual_report_name", "birthday", "gender", "maiden_name", "nick_name", "spouse_nick_name", "date_added", "alt_salutation", "alt_addressee", "honorary_name", "assistant_name", "marital_status_id", "marital_status_name", "is_anon", "created_at", "updated_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConstituentResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConstituentResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "external_constituent_id": obj.get("external_constituent_id"),
            "is_org": obj.get("is_org"),
            "constituent_contact_type_id": obj.get("constituent_contact_type_id"),
            "constituent_contact_type_name": obj.get("constituent_contact_type_name"),
            "prefix": obj.get("prefix"),
            "first_name": obj.get("first_name"),
            "middle_name": obj.get("middle_name"),
            "last_name": obj.get("last_name"),
            "suffix": obj.get("suffix"),
            "spouse_name": obj.get("spouse_name"),
            "org_name": obj.get("org_name"),
            "job_title": obj.get("job_title"),
            "addressee": obj.get("addressee"),
            "salutation": obj.get("salutation"),
            "sort_name": obj.get("sort_name"),
            "constituent_interest_level_id": obj.get("constituent_interest_level_id"),
            "constituent_interest_level_name": obj.get("constituent_interest_level_name"),
            "constituent_rating_id": obj.get("constituent_rating_id"),
            "constituent_rating_name": obj.get("constituent_rating_name"),
            "is_deceased": obj.get("is_deceased"),
            "deceased_date": obj.get("deceased_date"),
            "annual_report_name": obj.get("annual_report_name"),
            "birthday": obj.get("birthday"),
            "gender": obj.get("gender"),
            "maiden_name": obj.get("maiden_name"),
            "nick_name": obj.get("nick_name"),
            "spouse_nick_name": obj.get("spouse_nick_name"),
            "date_added": obj.get("date_added"),
            "alt_salutation": obj.get("alt_salutation"),
            "alt_addressee": obj.get("alt_addressee"),
            "honorary_name": obj.get("honorary_name"),
            "assistant_name": obj.get("assistant_name"),
            "marital_status_id": obj.get("marital_status_id"),
            "marital_status_name": obj.get("marital_status_name"),
            "is_anon": obj.get("is_anon"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


