# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from lgl_openapi_3_0_client.models.attendance_create import AttendanceCreate
from lgl_openapi_3_0_client.models.custom_attr_create import CustomAttrCreate
from lgl_openapi_3_0_client.models.custom_field_aggregated_update import CustomFieldAggregatedUpdate
from typing import Optional, Set
from typing_extensions import Self

class CreateBodyConst(BaseModel):
    """
    Body
    """ # noqa: E501
    event_id: StrictInt = Field(description="Event Id")
    parent_invitation_id: Optional[StrictInt] = Field(default=None, description="Parent Invitation Id (for additional guests)")
    notes: Optional[StrictStr] = Field(default=None, description="Notes")
    rsvp: Optional[StrictInt] = Field(default=None, description="RSVP (1-Yes, 2-No, 3-Maybe, 4-Unknown)")
    attended: Optional[StrictInt] = Field(default=None, description="Attended")
    assigned_to: Optional[StrictInt] = Field(default=None, description="Assigned to")
    attendee_names: Optional[StrictStr] = Field(default=None, description="Attendees Names")
    guest_first_name: Optional[StrictStr] = Field(default=None, description="Additional Guest First Name")
    guest_last_name: Optional[StrictStr] = Field(default=None, description="Additional Guest Last Name")
    is_a_guest: Optional[StrictBool] = Field(default=None, description="Creating an additional guest record")
    attendances: Optional[List[AttendanceCreate]] = Field(default=None, description="Multiple attendances")
    custom_fields: Optional[List[CustomFieldAggregatedUpdate]] = Field(default=None, description="Invitation custom fields (Categories)")
    custom_attrs: Optional[List[CustomAttrCreate]] = Field(default=None, description="Invitation custom attributes")
    __properties: ClassVar[List[str]] = ["event_id", "parent_invitation_id", "notes", "rsvp", "attended", "assigned_to", "attendee_names", "guest_first_name", "guest_last_name", "is_a_guest", "attendances", "custom_fields", "custom_attrs"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateBodyConst from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in attendances (list)
        _items = []
        if self.attendances:
            for _item_attendances in self.attendances:
                if _item_attendances:
                    _items.append(_item_attendances.to_dict())
            _dict['attendances'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in custom_fields (list)
        _items = []
        if self.custom_fields:
            for _item_custom_fields in self.custom_fields:
                if _item_custom_fields:
                    _items.append(_item_custom_fields.to_dict())
            _dict['custom_fields'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in custom_attrs (list)
        _items = []
        if self.custom_attrs:
            for _item_custom_attrs in self.custom_attrs:
                if _item_custom_attrs:
                    _items.append(_item_custom_attrs.to_dict())
            _dict['custom_attrs'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateBodyConst from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "event_id": obj.get("event_id"),
            "parent_invitation_id": obj.get("parent_invitation_id"),
            "notes": obj.get("notes"),
            "rsvp": obj.get("rsvp"),
            "attended": obj.get("attended"),
            "assigned_to": obj.get("assigned_to"),
            "attendee_names": obj.get("attendee_names"),
            "guest_first_name": obj.get("guest_first_name"),
            "guest_last_name": obj.get("guest_last_name"),
            "is_a_guest": obj.get("is_a_guest"),
            "attendances": [AttendanceCreate.from_dict(_item) for _item in obj["attendances"]] if obj.get("attendances") is not None else None,
            "custom_fields": [CustomFieldAggregatedUpdate.from_dict(_item) for _item in obj["custom_fields"]] if obj.get("custom_fields") is not None else None,
            "custom_attrs": [CustomAttrCreate.from_dict(_item) for _item in obj["custom_attrs"]] if obj.get("custom_attrs") is not None else None
        })
        return _obj


