# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class EmailAddressResponse(BaseModel):
    """
    A EmailAddress object.
    """ # noqa: E501
    id: StrictInt = Field(description="Email Address ID")
    item_id: StrictInt = Field(description="Owner ID")
    item_type: StrictStr = Field(description="Owner Type")
    address: Optional[StrictStr] = Field(default=None, description="Email Address")
    email_address_type_id: Optional[StrictInt] = Field(default=None, description="Email Address Type ID")
    email_type_name: Optional[StrictStr] = Field(default=None, description="Email Address Type Name")
    is_preferred: Optional[StrictBool] = Field(default=None, description="Make this the preferred email address")
    not_current: Optional[StrictBool] = Field(default=None, description="No longer a current email address")
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["id", "item_id", "item_type", "address", "email_address_type_id", "email_type_name", "is_preferred", "not_current", "created_at", "updated_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EmailAddressResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EmailAddressResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "item_id": obj.get("item_id"),
            "item_type": obj.get("item_type"),
            "address": obj.get("address"),
            "email_address_type_id": obj.get("email_address_type_id"),
            "email_type_name": obj.get("email_type_name"),
            "is_preferred": obj.get("is_preferred"),
            "not_current": obj.get("not_current"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


