# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from lgl_openapi_3_0_client.models.custom_field_aggregated_update import CustomFieldAggregatedUpdate
from typing import Optional, Set
from typing_extensions import Self

class Gift(BaseModel):
    """
    A Gift object.
    """ # noqa: E501
    external_id: Optional[StrictInt] = Field(default=None, description="External Gift ID")
    is_anon: Optional[StrictBool] = Field(default=None, description="Gift is Anonymous?")
    gift_type_id: StrictInt = Field(description="Gift type ID")
    gift_type_name: StrictStr = Field(description="Gift type name")
    gift_category_id: Optional[StrictInt] = Field(default=None, description="Gift category ID")
    gift_category_name: Optional[StrictStr] = Field(default=None, description="Gift category name")
    campaign_id: Optional[StrictInt] = Field(default=None, description="Campaign ID")
    campaign_name: Optional[StrictStr] = Field(default=None, description="Campaign name")
    fund_id: Optional[StrictInt] = Field(default=None, description="Fund ID")
    fund_name: Optional[StrictStr] = Field(default=None, description="Fund name")
    appeal_id: Optional[StrictInt] = Field(default=None, description="Appeal ID")
    appeal_name: Optional[StrictStr] = Field(default=None, description="Appeal name")
    event_id: Optional[StrictInt] = Field(default=None, description="Event ID")
    event_name: Optional[StrictStr] = Field(default=None, description="Event name")
    received_amount: Optional[Union[StrictFloat, StrictInt]] = None
    received_date: Optional[date] = None
    payment_type_id: Optional[StrictInt] = Field(default=None, description="Payment type ID")
    payment_type_name: Optional[StrictStr] = Field(default=None, description="Payment type name")
    check_number: Optional[StrictStr] = Field(default=None, description="Check/Reference No.")
    deductible_amount: Optional[Union[StrictFloat, StrictInt]] = None
    note: Optional[StrictStr] = Field(default=None, description="Gift note")
    ack_template_name: Optional[StrictStr] = Field(default=None, description="Ack. mailing template name. (use 'do_not_ack' to indicate no acknowledgment)")
    deposit_date: Optional[date] = None
    deposited_amount: Optional[Union[StrictFloat, StrictInt]] = None
    parent_gift_id: Optional[StrictInt] = Field(default=None, description="LGL parent gift ID")
    parent_external_id: Optional[StrictInt] = Field(default=None, description="External parent gift ID")
    auto_sync_to_qbo: Optional[StrictBool] = Field(default=None, description="Auto Sync to QBO (only for active QuickBooks integrations)")
    tribute_name: Optional[StrictStr] = Field(default=None, description="The name of tribute. Values: \"Honorary - General\", \"Memorial - General\", or a pre-defined named tribute")
    tributee_name: Optional[StrictStr] = Field(default=None, description="The name of the honoree/deceased")
    tribute_dedication: Optional[StrictStr] = Field(default=None, description="The tribute dedication note/text for a gift")
    tribute_recipient_name: Optional[StrictStr] = Field(default=None, description="The name of person who should be notified about this tribute gift.")
    tribute_recipient_salutation: Optional[StrictStr] = Field(default=None, description="The name of person who should be notified about this tribute gift.")
    tribute_recipient_email: Optional[StrictStr] = Field(default=None, description="The email of the person who should be notified about this tribute gift.")
    tribute_recipient_address: Optional[StrictStr] = Field(default=None, description="The address of the person who should be notified about this tribute gift.")
    tribute_recipient_notification_template: Optional[StrictStr] = Field(default=None, description="The notification template to be used for the person who should be notified about this tribute gift.")
    team_member: Optional[StrictStr] = Field(default=None, description="Team Member ('id', 'email', or 'first_name last_name')")
    custom_fields: Optional[List[CustomFieldAggregatedUpdate]] = Field(default=None, description="Gift custom fields (Categories)")
    __properties: ClassVar[List[str]] = ["external_id", "is_anon", "gift_type_id", "gift_type_name", "gift_category_id", "gift_category_name", "campaign_id", "campaign_name", "fund_id", "fund_name", "appeal_id", "appeal_name", "event_id", "event_name", "received_amount", "received_date", "payment_type_id", "payment_type_name", "check_number", "deductible_amount", "note", "ack_template_name", "deposit_date", "deposited_amount", "parent_gift_id", "parent_external_id", "auto_sync_to_qbo", "tribute_name", "tributee_name", "tribute_dedication", "tribute_recipient_name", "tribute_recipient_salutation", "tribute_recipient_email", "tribute_recipient_address", "tribute_recipient_notification_template", "team_member", "custom_fields"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Gift from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in custom_fields (list)
        _items = []
        if self.custom_fields:
            for _item_custom_fields in self.custom_fields:
                if _item_custom_fields:
                    _items.append(_item_custom_fields.to_dict())
            _dict['custom_fields'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Gift from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "external_id": obj.get("external_id"),
            "is_anon": obj.get("is_anon"),
            "gift_type_id": obj.get("gift_type_id"),
            "gift_type_name": obj.get("gift_type_name"),
            "gift_category_id": obj.get("gift_category_id"),
            "gift_category_name": obj.get("gift_category_name"),
            "campaign_id": obj.get("campaign_id"),
            "campaign_name": obj.get("campaign_name"),
            "fund_id": obj.get("fund_id"),
            "fund_name": obj.get("fund_name"),
            "appeal_id": obj.get("appeal_id"),
            "appeal_name": obj.get("appeal_name"),
            "event_id": obj.get("event_id"),
            "event_name": obj.get("event_name"),
            "received_amount": obj.get("received_amount"),
            "received_date": obj.get("received_date"),
            "payment_type_id": obj.get("payment_type_id"),
            "payment_type_name": obj.get("payment_type_name"),
            "check_number": obj.get("check_number"),
            "deductible_amount": obj.get("deductible_amount"),
            "note": obj.get("note"),
            "ack_template_name": obj.get("ack_template_name"),
            "deposit_date": obj.get("deposit_date"),
            "deposited_amount": obj.get("deposited_amount"),
            "parent_gift_id": obj.get("parent_gift_id"),
            "parent_external_id": obj.get("parent_external_id"),
            "auto_sync_to_qbo": obj.get("auto_sync_to_qbo"),
            "tribute_name": obj.get("tribute_name"),
            "tributee_name": obj.get("tributee_name"),
            "tribute_dedication": obj.get("tribute_dedication"),
            "tribute_recipient_name": obj.get("tribute_recipient_name"),
            "tribute_recipient_salutation": obj.get("tribute_recipient_salutation"),
            "tribute_recipient_email": obj.get("tribute_recipient_email"),
            "tribute_recipient_address": obj.get("tribute_recipient_address"),
            "tribute_recipient_notification_template": obj.get("tribute_recipient_notification_template"),
            "team_member": obj.get("team_member"),
            "custom_fields": [CustomFieldAggregatedUpdate.from_dict(_item) for _item in obj["custom_fields"]] if obj.get("custom_fields") is not None else None
        })
        return _obj


