# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from lgl_openapi_3_0_client.models.attendance import Attendance
from lgl_openapi_3_0_client.models.custom_attr import CustomAttr
from lgl_openapi_3_0_client.models.custom_field import CustomField
from typing import Optional, Set
from typing_extensions import Self

class InvitationsShow(BaseModel):
    """
    An Invitation object.
    """ # noqa: E501
    api_version: StrictStr
    id: Optional[StrictInt] = Field(default=None, description="Invitation Id")
    constituent_id: StrictInt = Field(description="Constituent Id")
    guest_name: Optional[StrictStr] = Field(default=None, description="Guest Name")
    is_a_guest: Optional[StrictBool] = Field(default=None, description="Creating an additional guest record")
    parent_invitation_id: Optional[StrictInt] = Field(default=None, description="Parent Invitation Id (for additional guests)")
    parent_invitation_guest_name: Optional[StrictStr] = Field(default=None, description="Parent Invitation Guest Name (for additional guests)")
    event_id: StrictInt = Field(description="Event Id")
    name: Optional[StrictStr] = Field(default=None, description="Event Name")
    notes: Optional[StrictStr] = Field(default=None, description="Notes")
    rsvp: Optional[StrictInt] = Field(default=None, description="RSVP (1-Yes, 2-No, 3-Maybe, 4-Unknown)")
    attended: Optional[StrictInt] = Field(default=None, description="Attended")
    raised: Optional[Union[StrictFloat, StrictInt]] = None
    status: Optional[StrictStr] = Field(default=None, description="Status")
    donated: Optional[StrictBool] = Field(default=None, description="Donated")
    assigned_to: Optional[StrictInt] = Field(default=None, description="Assigned to")
    additional_guests: Optional[StrictInt] = Field(default=None, description="Number of additional guests")
    attendees: Optional[StrictInt] = Field(default=None, description="Attendees")
    attendee_names: Optional[StrictStr] = Field(default=None, description="Attendees Names")
    attend_count: Optional[StrictInt] = Field(default=None, description="Attend Count")
    attendances: Optional[List[Attendance]] = Field(default=None, description="Multiple attendances")
    custom_fields: Optional[List[CustomField]] = Field(default=None, description="Invitation custom fields (Categories)")
    custom_attrs: Optional[List[CustomAttr]] = Field(default=None, description="Invitation custom attributes")
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["api_version", "id", "constituent_id", "guest_name", "is_a_guest", "parent_invitation_id", "parent_invitation_guest_name", "event_id", "name", "notes", "rsvp", "attended", "raised", "status", "donated", "assigned_to", "additional_guests", "attendees", "attendee_names", "attend_count", "attendances", "custom_fields", "custom_attrs", "created_at", "updated_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InvitationsShow from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in attendances (list)
        _items = []
        if self.attendances:
            for _item_attendances in self.attendances:
                if _item_attendances:
                    _items.append(_item_attendances.to_dict())
            _dict['attendances'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in custom_fields (list)
        _items = []
        if self.custom_fields:
            for _item_custom_fields in self.custom_fields:
                if _item_custom_fields:
                    _items.append(_item_custom_fields.to_dict())
            _dict['custom_fields'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in custom_attrs (list)
        _items = []
        if self.custom_attrs:
            for _item_custom_attrs in self.custom_attrs:
                if _item_custom_attrs:
                    _items.append(_item_custom_attrs.to_dict())
            _dict['custom_attrs'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InvitationsShow from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "api_version": obj.get("api_version"),
            "id": obj.get("id"),
            "constituent_id": obj.get("constituent_id"),
            "guest_name": obj.get("guest_name"),
            "is_a_guest": obj.get("is_a_guest"),
            "parent_invitation_id": obj.get("parent_invitation_id"),
            "parent_invitation_guest_name": obj.get("parent_invitation_guest_name"),
            "event_id": obj.get("event_id"),
            "name": obj.get("name"),
            "notes": obj.get("notes"),
            "rsvp": obj.get("rsvp"),
            "attended": obj.get("attended"),
            "raised": obj.get("raised"),
            "status": obj.get("status"),
            "donated": obj.get("donated"),
            "assigned_to": obj.get("assigned_to"),
            "additional_guests": obj.get("additional_guests"),
            "attendees": obj.get("attendees"),
            "attendee_names": obj.get("attendee_names"),
            "attend_count": obj.get("attend_count"),
            "attendances": [Attendance.from_dict(_item) for _item in obj["attendances"]] if obj.get("attendances") is not None else None,
            "custom_fields": [CustomField.from_dict(_item) for _item in obj["custom_fields"]] if obj.get("custom_fields") is not None else None,
            "custom_attrs": [CustomAttr.from_dict(_item) for _item in obj["custom_attrs"]] if obj.get("custom_attrs") is not None else None,
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


