# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class RelationshipTypeResponse(BaseModel):
    """
    A RelationshipType object.
    """ # noqa: E501
    id: StrictInt = Field(description="ID")
    name: StrictStr = Field(description="Name")
    short_code: Optional[StrictStr] = Field(default=None, description="Short Code")
    type_code: Optional[StrictStr] = Field(default=None, description="Type Code")
    ordinal: Optional[StrictInt] = Field(default=None, description="Ordinal")
    reciprocal_id: Optional[StrictInt] = Field(default=None, description="Reciprocal Id")
    auto_soft_credit: Optional[StrictInt] = Field(default=None, description="Automatically soft credit?")
    is_spouse_partner: Optional[StrictBool] = Field(default=None, description="Is Spouse Partner?")
    __properties: ClassVar[List[str]] = ["id", "name", "short_code", "type_code", "ordinal", "reciprocal_id", "auto_soft_credit", "is_spouse_partner"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RelationshipTypeResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RelationshipTypeResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "short_code": obj.get("short_code"),
            "type_code": obj.get("type_code"),
            "ordinal": obj.get("ordinal"),
            "reciprocal_id": obj.get("reciprocal_id"),
            "auto_soft_credit": obj.get("auto_soft_credit"),
            "is_spouse_partner": obj.get("is_spouse_partner")
        })
        return _obj


