# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date, datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class StreetAddressResponse(BaseModel):
    """
    A StreetAddress object.
    """ # noqa: E501
    id: StrictInt = Field(description="Email Address ID")
    item_id: StrictInt = Field(description="Owner ID")
    item_type: StrictStr = Field(description="Owner Type")
    street: Optional[StrictStr] = Field(default=None, description="Street")
    city: Optional[StrictStr] = Field(default=None, description="City")
    state: Optional[StrictStr] = Field(default=None, description="State/Province")
    country: Optional[StrictStr] = Field(default=None, description="Country")
    postal_code: Optional[StrictStr] = Field(default=None, description="Zip/Postal Code")
    county: Optional[StrictStr] = Field(default=None, description="County")
    street_address_type_id: Optional[StrictInt] = Field(default=None, description="Street Address Type ID")
    street_type_name: Optional[StrictStr] = Field(default=None, description="Street Address Type Name")
    is_preferred: Optional[StrictBool] = Field(default=None, description="Is preferred address")
    not_current: Optional[StrictBool] = Field(default=None, description="Not current?")
    seasonal_from: Optional[StrictStr] = Field(default=None, description="Seasonal from (mm-dd)")
    seasonal_to: Optional[StrictStr] = Field(default=None, description="Seasonal to (mm-dd)")
    seasonal: Optional[StrictBool] = Field(default=None, description="Is seasonal?")
    lat: Optional[Union[StrictFloat, StrictInt]] = None
    lng: Optional[Union[StrictFloat, StrictInt]] = None
    zip5: Optional[StrictStr] = Field(default=None, description="5 digit zipcode")
    verified: Optional[StrictBool] = Field(default=None, description="Is verified?")
    verified_on: Optional[date] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["id", "item_id", "item_type", "street", "city", "state", "country", "postal_code", "county", "street_address_type_id", "street_type_name", "is_preferred", "not_current", "seasonal_from", "seasonal_to", "seasonal", "lat", "lng", "zip5", "verified", "verified_on", "created_at", "updated_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StreetAddressResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StreetAddressResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "item_id": obj.get("item_id"),
            "item_type": obj.get("item_type"),
            "street": obj.get("street"),
            "city": obj.get("city"),
            "state": obj.get("state"),
            "country": obj.get("country"),
            "postal_code": obj.get("postal_code"),
            "county": obj.get("county"),
            "street_address_type_id": obj.get("street_address_type_id"),
            "street_type_name": obj.get("street_type_name"),
            "is_preferred": obj.get("is_preferred"),
            "not_current": obj.get("not_current"),
            "seasonal_from": obj.get("seasonal_from"),
            "seasonal_to": obj.get("seasonal_to"),
            "seasonal": obj.get("seasonal"),
            "lat": obj.get("lat"),
            "lng": obj.get("lng"),
            "zip5": obj.get("zip5"),
            "verified": obj.get("verified"),
            "verified_on": obj.get("verified_on"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


