# coding: utf-8

"""
    Little Green Light

    REST application programming language for JSON.

    The version of the OpenAPI document: json
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date, datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from lgl_openapi_3_0_client.models.custom_field import CustomField
from typing import Optional, Set
from typing_extensions import Self

class VolunteerTimeResponse(BaseModel):
    """
    A VolunteerTime object.
    """ # noqa: E501
    id: StrictInt = Field(description="Volunteer Time ID")
    constituent_id: StrictInt = Field(description="Constituent ID")
    external_id: Optional[StrictInt] = Field(default=None, description="External Volunteering ID")
    volunteering_category_id: StrictInt = Field(description="Volunteer Category Id")
    volunteering_category_name: Optional[StrictStr] = Field(default=None, description="Volunteer Category Name")
    description: Optional[StrictStr] = Field(default=None, description="Description")
    hours: Optional[Union[StrictFloat, StrictInt]] = None
    var_date: Optional[date] = Field(default=None, alias="date")
    end_date: Optional[date] = None
    completed_hours: Optional[Union[StrictFloat, StrictInt]] = None
    custom_fields: Optional[List[CustomField]] = Field(default=None, description="VolunteerTime custom fields (Categories)")
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["id", "constituent_id", "external_id", "volunteering_category_id", "volunteering_category_name", "description", "hours", "date", "end_date", "completed_hours", "custom_fields", "created_at", "updated_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VolunteerTimeResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in custom_fields (list)
        _items = []
        if self.custom_fields:
            for _item_custom_fields in self.custom_fields:
                if _item_custom_fields:
                    _items.append(_item_custom_fields.to_dict())
            _dict['custom_fields'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VolunteerTimeResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "constituent_id": obj.get("constituent_id"),
            "external_id": obj.get("external_id"),
            "volunteering_category_id": obj.get("volunteering_category_id"),
            "volunteering_category_name": obj.get("volunteering_category_name"),
            "description": obj.get("description"),
            "hours": obj.get("hours"),
            "date": obj.get("date"),
            "end_date": obj.get("end_date"),
            "completed_hours": obj.get("completed_hours"),
            "custom_fields": [CustomField.from_dict(_item) for _item in obj["custom_fields"]] if obj.get("custom_fields") is not None else None,
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


